//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Device_Licence_Control {
    public partial class Dashboard {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlAdminButton;
        protected global::System.Web.UI.WebControls.HyperLink hlAdminPanel;
        protected global::System.Web.UI.WebControls.Literal litUserName;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlAdminNotice;
        protected global::System.Web.UI.WebControls.HyperLink hlViewProfile;
        protected global::System.Web.UI.WebControls.HyperLink hlMyDeviceLicenses;
        protected global::System.Web.UI.WebControls.HyperLink hlMyDevices;
        protected global::System.Web.UI.WebControls.HyperLink hlCreateKey;
        protected global::System.Web.UI.WebControls.HyperLink hlAssignment;
    }
}
