//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Device_Licence_Control
{
    public partial class Register
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        protected global::System.Web.UI.WebControls.TextBox txtCity;

        protected global::System.Web.UI.WebControls.TextBox txtCountry;

        protected global::System.Web.UI.WebControls.TextBox txtEmail1;

        protected global::System.Web.UI.WebControls.Button btnAddEmail;

        protected global::System.Web.UI.WebControls.Panel pnlAdditionalEmails;

        protected global::System.Web.UI.WebControls.Repeater rptEmails;

        protected global::System.Web.UI.WebControls.TextBox txtPhone1;

        protected global::System.Web.UI.WebControls.Button btnAddPhone;

        protected global::System.Web.UI.WebControls.Panel pnlAdditionalPhones;

        protected global::System.Web.UI.WebControls.Repeater rptPhones;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        protected global::System.Web.UI.WebControls.Button btnRegister;

        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
