//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Device_Licence_Control
{
    public partial class RegisteredDevices
    {
        protected global::System.Web.UI.WebControls.Literal litUserName;
        protected global::System.Web.UI.WebControls.HyperLink hlAdminPanel;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.HyperLink hlBack;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.DropDownList ddlUser;
        protected global::System.Web.UI.WebControls.DropDownList ddlDeviceType;
        protected global::System.Web.UI.WebControls.TextBox txtDeviceName;
        protected global::System.Web.UI.WebControls.TextBox txtSerialNumber;
        protected global::System.Web.UI.WebControls.TextBox txtRegisterDate;
        protected global::System.Web.UI.WebControls.Button btnRegisterDevice;
        protected global::System.Web.UI.WebControls.Panel pnlDevicesList;
        protected global::System.Web.UI.WebControls.GridView gvRegisteredDevices;
        protected global::System.Web.UI.WebControls.Panel pnlNoDevices;
    }
}
