//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Device_Licence_Control
{
    public partial class ViewProfile
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.HyperLink hlDashboard;
        protected global::System.Web.UI.WebControls.Literal litUserName;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Literal litFullName;
        protected global::System.Web.UI.WebControls.Literal litUserId;
        protected global::System.Web.UI.WebControls.Literal litProfileFullName;
        protected global::System.Web.UI.WebControls.Literal litRole;
        protected global::System.Web.UI.WebControls.Literal litStatus;
        protected global::System.Web.UI.WebControls.Literal litCreatedDate;
        protected global::System.Web.UI.WebControls.HyperLink hlEdit;
    }
}
